//Types para alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//Types para actividades
export const MOSTRAR_ACTIVIDAD_VIDEOS = 'MOSTRAR_ACTIVIDAD_VIDEOS';
export const MOSTRAR_ACTIVIDAD_EJEMPLOS = 'MOSTRAR_ACTIVIDAD_EJEMPLOS';
export const MOSTRAR_ACTIVIDAD_PRACTICA = 'MOSTRAR_ACTIVIDAD_PRACTICA';
export const MOSTRAR_ACTIVIDAD_JUEGA = 'MOSTRAR_ACTIVIDAD_JUEGA';
export const OCULTAR_ACTIVIDADES = 'OCULTAR_ACTIVIDADES';

//Types para opciones
export const MOSTRAR_OPCION_CAMBIOS = 'MOSTRAR_OPCION_CAMBIOS';
export const MOSTRAR_OPCION_PROGRESO = 'MOSTRAR_OPCION_PROGRESO';
export const OCULTAR_OPCIONES = 'OCULTAR_OPCIONES';

//Types para la actividad de ejemplos
export const SELECCIONAR_EJEMPLO = 'SELECCIONAR_EJEMPLO';
export const MOSTRAR_EJEMPLO = 'MOSTRAR_EJEMPLO';
export const OCULTAR_EJEMPLO = 'OCULTAR_EJEMPLO';

//Types para la autenticación del niño
export const OBTENER_USUARIO_NINO = 'OBTENER_USUARIO_NINO';
export const LOGIN_EXITOSO_NINO = 'LOGIN_EXITOSO_NINO';
export const LOGIN_ERROR_NINO = 'LOGIN_ERROR_NINO';
export const CERRAR_SESION_NINO = 'CERRAR_SESION_NINO';

//Types para la autenticación del padre o tutor
export const REGISTRO_EXITOSO_PADRE = 'REGISTRO_EXITOSO_PADRE';
export const REGISTRO_ERROR_PADRE = 'REGISTRO_ERROR_PADRE';
export const OBTENER_USUARIO_PADRE = 'OBTENER_USUARIO_PADRE';
export const LOGIN_EXITOSO_PADRE = 'LOGIN_EXITOSO_PADRE';
export const LOGIN_ERROR_PADRE = 'LOGIN_ERROR_PADRE';
export const CERRAR_SESION_PADRE = 'CERRAR_SESION_PADRE';
export const OBTENER_NINO_TUTOR = 'OBTENER_NINO_TUTOR';